name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
    - name: Put secrets
      run: echo $${{ secrets.DBPASSWORD }} >> db_password && echo ${{ secrets.APPSETTINGS }} >> appsettings.json && echo ${{ secrets.ENV_BACK }} >> .env_backend
    - name: Run docker compose
      run: docker compose up -f docker-compose.prod.yaml --pull
