name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: checkout
      uses: actions/checkout@v4
    - name: Put secrets
      env:
        DBPASSWORD: ${{ secrets.DBPASSWORD }}
        APPSETTINGS: ${{ secrets.APPSETTINGS }}
        ENV_BACK: ${{ secrets.ENV_BACK }}
      run: echo "$DBPASSWORD" >> db_password && echo "$APPSETTINGS" >> appsettings.json && echo "$ENV_BACK" >> .env_backend
    - name: Run docker compose
      run: docker compose -f docker-compose.prod.yaml up --pull always
